# Generated by Django 2.0.9 on 2018-12-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='', max_length=100)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='Images/None/no-img.jpg', upload_to='Images/')),
            ],
        ),
    ]
